//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finansisto.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Finansisto.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Актив.
        /// </summary>
        internal static string AccountTypeAsset {
            get {
                return ResourceManager.GetString("AccountTypeAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банковский счет.
        /// </summary>
        internal static string AccountTypeBank {
            get {
                return ResourceManager.GetString("AccountTypeBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличные.
        /// </summary>
        internal static string AccountTypeCash {
            get {
                return ResourceManager.GetString("AccountTypeCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кредитная карта.
        /// </summary>
        internal static string AccountTypeCreditCard {
            get {
                return ResourceManager.GetString("AccountTypeCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дебетовая карта.
        /// </summary>
        internal static string AccountTypeDebitCard {
            get {
                return ResourceManager.GetString("AccountTypeDebitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пассив.
        /// </summary>
        internal static string AccountTypeLiability {
            get {
                return ResourceManager.GetString("AccountTypeLiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другой.
        /// </summary>
        internal static string AccountTypeOther {
            get {
                return ResourceManager.GetString("AccountTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        internal static string AccountTypePayPal {
            get {
                return ResourceManager.GetString("AccountTypePayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экземпляр типа {0} не может быть активирован из строки таблицы {1}..
        /// </summary>
        internal static string InvalidEntityDataRow {
            get {
                return ResourceManager.GetString("InvalidEntityDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение {0} не определено для типа {1}..
        /// </summary>
        internal static string InvalidEntityEnumValue {
            get {
                return ResourceManager.GetString("InvalidEntityEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Express.
        /// </summary>
        internal static string PaymentSystemAmex {
            get {
                return ResourceManager.GetString("PaymentSystemAmex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diners Club.
        /// </summary>
        internal static string PaymentSystemDiners {
            get {
                return ResourceManager.GetString("PaymentSystemDiners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        internal static string PaymentSystemDiscover {
            get {
                return ResourceManager.GetString("PaymentSystemDiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JCB.
        /// </summary>
        internal static string PaymentSystemJcb {
            get {
                return ResourceManager.GetString("PaymentSystemJcb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maestro.
        /// </summary>
        internal static string PaymentSystemMaestro {
            get {
                return ResourceManager.GetString("PaymentSystemMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterCard.
        /// </summary>
        internal static string PaymentSystemMasterCard {
            get {
                return ResourceManager.GetString("PaymentSystemMasterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETS.
        /// </summary>
        internal static string PaymentSystemNets {
            get {
                return ResourceManager.GetString("PaymentSystemNets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnionPay.
        /// </summary>
        internal static string PaymentSystemUnionPay {
            get {
                return ResourceManager.GetString("PaymentSystemUnionPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISA.
        /// </summary>
        internal static string PaymentSystemVisa {
            get {
                return ResourceManager.GetString("PaymentSystemVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISA Electron.
        /// </summary>
        internal static string PaymentSystemVisaElectron {
            get {
                return ResourceManager.GetString("PaymentSystemVisaElectron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Занесено.
        /// </summary>
        internal static string TransactionStatusCleared {
            get {
                return ResourceManager.GetString("TransactionStatusCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидается.
        /// </summary>
        internal static string TransactionStatusPending {
            get {
                return ResourceManager.GetString("TransactionStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выверено.
        /// </summary>
        internal static string TransactionStatusReconciled {
            get {
                return ResourceManager.GetString("TransactionStatusReconciled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановлено.
        /// </summary>
        internal static string TransactionStatusRestored {
            get {
                return ResourceManager.GetString("TransactionStatusRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выверено.
        /// </summary>
        internal static string TransactionStatusUnreconciled {
            get {
                return ResourceManager.GetString("TransactionStatusUnreconciled", resourceCulture);
            }
        }
    }
}
